namespace GameLogic.Registry;

using System.Text.Json;

/// <summary>
/// A union of reference types for the registry. References can be:
/// - Pure reference: A template id
/// - Reference with an override: A template id with an override
/// - Inline reference: An inline definition of a template
/// - Reference with an instance id: An instance with a template id
/// </summary>
public abstract record ReferenceUnionSpec
{
    public required EReferenceType ReferenceType { get; init; }
    public required ETemplateType TemplateType { get; init; }
};

/// <summary>
/// How a reference union spec is to be interpreted.
/// </summary>
public enum EReferenceType
{
    // A pure reference to a template. No overrides are allowed.
    Ref,

    // A reference to a template with an override.
    Override,

    // An inline definition of a template.
    Inline,

    // A reference to an instance with a template id. Create an instance id if not provided.
    Instance,
}

/// <summary>
/// What type of object a reference union spec creates.
/// </summary>
public enum ETemplateType
{
    // A character template.
    Character,

    // An item template.
    Item,

    // A skill template.
    Skill,

    // A usable template.
    Usable,

    // An effect template.
    Effect,
}

public interface ITemplateOverride<TTemplate> { }

public sealed record OverrideSpec<TTemplate, TOverride> : ReferenceUnionSpec
    where TTemplate : ITemplate
    where TOverride : ITemplateOverride<TTemplate>
{
    public required TemplateId TemplateId { get; init; }
    public required TOverride Override { get; init; }
};

/// <summary>
/// A pure reference to a template. No overrides are allowed.
/// </summary>
public sealed record RefSpec : ReferenceUnionSpec
{
    public required TemplateId TemplateId { get; init; }
};


/// <summary>
/// An inline definition of a template. Will need to have a template id
/// generated by the registry at runtime.
/// </summary>
public sealed record InlineSpec<TTemplate> : ReferenceUnionSpec
    where TTemplate : ITemplate
{
    public required TTemplate Template { get; init; }
};

/// <summary>
/// A reference to an instance with a template id. As it is an instance,
/// overrides are not only allowed, but expected.
/// </summary>
public sealed record InstanceSpec<TTemplate, TOverride> : ReferenceUnionSpec
    where TTemplate : ITemplate
    where TOverride : ITemplateOverride<TTemplate>
{
    public required TemplateId TemplateId { get; init; }
    public InstanceId InstanceId { get; init; } = Ids.Instance(); // optional; generate if null
    // TODO: Include custom TInstance fields to use instead of TTemplate again
    public TTemplate? Instance { get; init; } // optional
};
