namespace GameLogic.Registry;

using System.Text.Json;
using GameLogic.Entities.Characters;
using GameLogic.Entities.Skills;
using GameLogic.Usables;
using GameLogic.Usables.Effects;

/// <summary>
/// A union of reference types for the registry. References can be:
/// - Pure reference: A template id
/// - Reference with an override: A template id with an override
/// - Inline reference: An inline definition of a template
/// - Reference with an instance id: An instance with a template id
/// </summary>
public record ReferenceUnionSpec
{
    public required ReferenceUnionMetadata Metadata { get; init; }
};

// TODO: Ask chat how to support sub types of stats or other classes in factory
public record ReferenceUnionMetadata
{
    public required EReferenceKind Kind { get; init; }
    public required ETemplateType TemplateType { get; init; }
    public ETemplateSubType TemplateSubType { get; init; } = ETemplateSubType.None;

    public TemplateId TemplateId { get; init; } = Ids.NewTemplateId();
};

/// <summary>
/// How a reference union spec is to be interpreted.
/// </summary>
public enum EReferenceKind
{
    // A pure reference to a template. No overrides are allowed.
    Ref,

    // A reference to a template with an override.
    Override,

    // An inline definition of a template.
    Inline,

    // A reference to an instance with a template id. Create an instance id if not provided.
    Instance,
}

public interface ITemplateOverride<TTemplate> { }

public sealed record OverrideSpec<TTemplate, TOverride> : ReferenceUnionSpec
    where TOverride : ITemplateOverride<TTemplate>
{
    public required TOverride Override { get; init; }
};

/// <summary>
/// A pure reference to a template. No overrides are allowed.
/// </summary>
public sealed record RefSpec : ReferenceUnionSpec { };

/// <summary>
/// An inline definition of a template. Will need to have a template id
/// generated by the registry at runtime.
/// </summary>
public sealed record InlineSpec<TTemplate> : ReferenceUnionSpec
{
    public required TTemplate Template { get; init; }
};

/// <summary>
/// A reference to an instance with a template id. As it is an instance,
/// overrides are not only allowed, but expected.
/// </summary>
public sealed record InstanceSpec<TTemplate, TInstance> : ReferenceUnionSpec
{
    // TODO: Include custom TInstance fields to use instead of TTemplate again
    public InstanceId InstanceId { get; init; } = Ids.Instance();
    public TInstance? Instance { get; init; } // optional
};

public static class TemplateTypeMaps
{
    public static readonly Dictionary<
        ETemplateType,
        (Type TemplateType, Type TemplateOverrideType)
    > ETemplateTypeToOverrideType = new()
    {
        {
            ETemplateType.Character,
            (typeof(CharacterTemplateRecord), typeof(CharacterOverrideRecord))
        },
        { ETemplateType.Skill, (typeof(SkillTemplateRecord), typeof(SkillOverrideRecord)) },
        { ETemplateType.Usable, (typeof(UsableTemplateRecord), typeof(UsableOverrideRecord)) },
        { ETemplateType.Effect, (typeof(EffectTemplateRecord), typeof(EffectOverrideRecord)) },
    };

    public static readonly Dictionary<ETemplateType, Type> ETemplateTypeToTemplateType = new()
    {
        { ETemplateType.Character, typeof(CharacterTemplateRecord) },
        { ETemplateType.Skill, typeof(SkillTemplateRecord) },
        { ETemplateType.Usable, typeof(UsableTemplateRecord) },
        { ETemplateType.Effect, typeof(EffectTemplateRecord) },
    };
}
