namespace GameLogic.Registry;

using System.Text.Json;
using GameLogic.Entities.Characters;
using GameLogic.Entities.Skills;
using GameLogic.Usables;
using GameLogic.Usables.Effects;

/// <summary>
/// A union of reference types for the registry. References can be:
/// - Pure reference: A template id
/// - Reference with an override: A template id with an override
/// - Inline reference: An inline definition of a template
/// - Reference with an instance id: An instance with a template id
/// </summary>
public record ReferenceSpec
{
    public required ReferenceMetadata Metadata { get; init; }
};

public record ReferenceSpec<TSpec> : ReferenceSpecBase<TSpec> where TSpec : ReferenceSpecBase<TSpec> {
    public required TSpec Spec { get; init; }
 }

// TODO: Ask chat how to support sub types of stats or other classes in factory
public record ReferenceMetadata
{
    public required EReferenceKind Kind { get; init; }
    public required ETemplateType TemplateType { get; init; }
    public ETemplateSubType TemplateSubType { get; init; } = ETemplateSubType.None;

    // TODO: Remove TemplateId and use ReferenceId instead. Used to identify the template in the registry
    public TemplateId TemplateId { get; init; } = Ids.NewTemplateId();

    // Used to identify the reference in the registry
    public ReferenceId ReferenceId { get; init; } = Ids.NewReferenceId();

    // Used to identify the dependency in the registry
    public ReferenceId? DependencyId { get; init; } = null;
};

/// <summary>
/// How a reference union spec is to be interpreted.
/// </summary>
public enum EReferenceKind
{
    // A pure reference to a template. No overrides are allowed.
    Ref,

    // A reference to a template with an override.
    Override,

    // An inline definition of a template.
    Inline,

    // A reference to an instance with a template id. Create an instance id if not provided.
    Instance,
}

public interface ITemplateOverride<TTemplate> { }

public sealed record OverrideSpec<TTemplate, TOverride> : ReferenceSpec
{
    public required TOverride Override { get; init; }
};

/// <summary>
/// A pure reference to a template. No overrides are allowed.
/// </summary>
public sealed record RefSpec : ReferenceSpec { };

/// <summary>
/// An inline definition of a template. Will need to have a template id
/// generated by the registry at runtime.
/// </summary>
public sealed record InlineSpec<TTemplate> : ReferenceSpec
{
    public required TTemplate Template { get; init; }
};

/// <summary>
/// A reference to an instance with a template id. As it is an instance,
/// overrides are not only allowed, but expected.
/// </summary>
public sealed record InstanceSpec<TTemplate, TInstance> : ReferenceSpec
{
    // TODO: Include custom TInstance fields to use instead of TTemplate again
    public required TInstance Instance { get; init; } // optional
};

public static class TemplateTypeMaps
{
    public static readonly Dictionary<
        ETemplateType,
        (Type TemplateType, Type TemplateOverrideType)
    > ETemplateTypeToOverrideType = new()
    {
        {
            ETemplateType.Character,
            (typeof(CharacterTemplateSpec), typeof(CharacterOverrideSpec))
        },
        { ETemplateType.Skill, (typeof(SkillTemplateSpec), typeof(SkillOverrideSpec)) },
        { ETemplateType.Usable, (typeof(UsableTemplateSpec), typeof(UsableOverrideSpec)) },
        { ETemplateType.Effect, (typeof(EffectTemplateSpec), typeof(EffectOverrideSpec)) },
    };

    public static readonly Dictionary<ETemplateType, Type> ETemplateTypeToTemplateType = new()
    {
        { ETemplateType.Character, typeof(CharacterTemplateSpec) },
        { ETemplateType.Skill, typeof(SkillTemplateSpec) },
        { ETemplateType.Usable, typeof(UsableTemplateSpec) },
        { ETemplateType.Effect, typeof(EffectTemplateSpec) },
    };
}
